settings:
  #Messages that players will recieve
  notify: true
  #Use shift + right click to set infinite anvil or shift + left click to remove infinite anvil
  shift-click: true
  #Max block radius for /anvil set [radius] and /anvil remove [radius] == %radius%
  max-radius: 25
  #Players require infiniteanvil.remove to remove an infinite anvil
  protect-infinite-anvils: true
  #Players with infiniteanvil.updates will recieve messages if plugin is not up to date
  CheckUpdate: true
  #If set to true, you will always recieve messages in console, that will inform you about version of the plugin
  ConsoleCheckUpdate: true
  #If set to true, default anvil crafting will be removed
  RemoveAnvilRecipe: false
  #If set to true, custom anvil crafting will be added (to remove default crafting, just set RemoveAnvilRecipe to true)
  CustomAnvilRecipe: false
  #Plugin Prefix
  Prefix: '&7[Infinite Anvil] '
  #Set your lang file
  Language: "en_US"
  #If true, custom names will be enabled
  Name: true
  #If true, custom lores will be enabled
  Lore: true
recipe:
  #To set AIR just write AIR (I don't want "" or '')
  #Recipe Shape
  # A | B | C
  # D | E | F
  # G | H | I
  A: IRON_INGOT
  B: IRON_INGOT
  C: IRON_INGOT
  D: null
  E: IRON_BLOCK
  F: null
  G: IRON_BLOCK
  H: IRON_BLOCK
  I: IRON_BLOCK
