settings:
  #Messages that players will recieve
  notify: true
  #Use shift + right click to set infinite anvil or shift + left click to remove infinite anvil
  shift-click: true
  #Max block radius for /anvil set [radius] and /anvil remove [radius] == %radius%
  max-radius: 25
  #Players require infiniteanvil.remove to remove an infinite anvil
  protect-infinite-anvils: true
  #Players with infiniteanvil.updates will recieve messages if plugin is not up to date
  CheckUpdate: true
  #If set to true, you will always recieve messages in console, that will inform you about version of the plugin
  ConsoleCheckUpdate: true
  #If set to true, anvil crafting will be removed
  RemoveAnvilRecipe: false
  #Plugin Prefix
  Prefix: '&7[Infinite Anvil] '
  #Set your lang file
  Language: "en_US"
