name: InfiniteAnvil
version: 2.1
description: Make your anvil unbreakable
author: nato3623
main: com.relumcommunity.infiniteanvil.main.Main
api-version: 1.13

commands:
  anvil:
    aliases: [anvils, infiniteanvil, ianvil, ia]
    description: recieve a complete list of available commands
    usage: /anvil help
