name: InfiniteAnvil
version: 1.6
description: Make your anvil unbreakable
author: nato3623
main: com.vaincecraft.infiniteanvil.main.Main

commands:
  anvil:
    aliases: [anvils, infiniteanvil, ianvil, ia]
    description: recieve a complete list of available commands
    usage: /anvil
